### ISSUE TITLE
View arbitrary image data from pointer

### ISSUE THREAD

**Issue by wziard** [OpenImageDebugger/OpenImageDebugger#25] opened 2021-05-05 13:35 UTC
Hi. This project looks extremely interesting.

Would it be hard to add a way to view a generic block of memory as an image? Filling in the needed info for width/height/stride/pixelformat just like you can specify the min/ax rgba values?

**Comment by csantosbh** [comment] 2021-06-05 20:08
Hello! That would be quite easy. You can do it yourself by defining a custom buffer (see https://github.com/OpenImageDebugger/OpenImageDebugger#advanced-configuration), with pixel type uint8 and 1 channel. You can use OpenCV's or Eigen's buffer types as examples.

If however you want to display the buffer content with a different format (e.g. hexadecimal values) you would need to create an additional data type and implement the corresponding visualization for it. I'm currently unable to implement this myself but pull requests are always welcome :)

**Comment by brunoalr** [comment] 2021-06-24 18:05
@csantosbh I guess this a duplicate from https://github.com/OpenImageDebugger/OpenImageDebugger/issues/30 (which I origininally proposed in the GIW repo)

**Comment by brunoalr** [comment] 2021-06-27 10:38
Closing as duplicate of #30

**Closed by brunoalr** 2021-06-27 10:38 UTC
